version: "2"
checks:
  similar-code:
    enabled: false
    config:
      languages:
      - javascript
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_patterns:
- node_modules/
- __test__/