version: '3'
services:

  # Nodejs
  knex-express-template:
    image: firmanjs/knex-express-template:dev
    container_name: knex-express-template
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    networks:
      express-template-network:
    restart: unless-stopped
    volumes:
      - .:/usr/apps/knex-express-template
      - /usr/apps/knex-express-template/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"

  # Postgre
  db-postgres:
    container_name: postgre-template
    command: postgres -c port=${POSTGRES_PORT}
    image: postgres:14.3-alpine3.15
    env_file:
      - .env
    networks:
      - express-template-network
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgre_template:/var/lib/postgresql/data

networks:
  express-template-network:
    driver: bridge