version: '3'
services:
  # Nodejs
  knex-express-template:
    image: firmanjs/knex-express-template:dev
    container_name: knex-express-template
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    networks:
      express-template-network:
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/apps/knex-express-template
      - /usr/apps/knex-express-template/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'
networks:
  express-template-network:
    driver: bridge
