version: '3'
services:

  # Nodejs
  knex-express-template:
    image: firmanjs/knex-express-template:stg
    container_name: knex-express-template
    build:
      context: .
      dockerfile: ./docker/Dockerfile.stg
    networks:
      express-template-network:
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
networks:
  express-template-network:
    driver: bridge