version: '3'
services:
  # Nodejs
  knex-express-template:
    image: firmanjs/knex-express-template:dev
    container_name: knex-express-template
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    networks:
      database_postgre-local:
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/apps/knex-express-template
      - /usr/apps/knex-express-template/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'

networks:
  database_postgre-local:
    external: true
