version: "3"
services:
  # Nodejs
  knex-express-template:
    image: firmanjs/knex-express-template:prod
    container_name: knex-express-template
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      database_postgre-local:
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"

networks:
  database_postgre-local:
    external: true

# for stand alone setup
# networks:
#   express-template-network:
#     driver: bridge
