FROM node:18.12.1-buster-slim

WORKDIR /usr/apps/knex-express-template

RUN rm -rf /var/cache/apk/*
RUN apt-get update && \
    apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

LABEL maintainer="firmanjs"

ENV NODE_ENV development
ENV TZ Asia/Jakarta

COPY package.json /usr/apps/knex-express-template/

RUN yarn install && yarn global add knex && yarn cache clean --all

CMD ["yarn", "dev"]