FROM node:alpine3.18

RUN rm -rf /var/cache/apk/*

LABEL maintainer="firmanjs"

WORKDIR /usr/apps/knex-express-template

ENV NODE_ENV development

COPY package.json /usr/apps/knex-express-template/

COPY . /usr/apps/knex-express-template/

COPY src/lang/locale build/lang/locale

RUN yarn install && yarn global add ts-node && yarn global add knex && yarn cache clean --all

CMD ["yarn", "dev"]