FROM node:18.12.1-buster-slim

RUN rm -rf /var/cache/apk/*

LABEL maintainer="firman"

WORKDIR /usr/apps/knex-express-template

COPY package.json ./

COPY tsconfig.json ./

RUN yarn install --frozen-lockfile --production && yarn add typescript

COPY . .

RUN yarn build

COPY knexfile.js ./

ENV NODE_ENV=production

COPY src/lang/locale build/lang

CMD ["yarn", "start"]