FROM node:18.12.1-buster-slim

RUN rm -rf /var/cache/apk/*

LABEL maintainer="firmanjs"

WORKDIR /usr/apps/knex-express-template

ENV NODE_ENV development

COPY package.json /usr/apps/knex-express-template/

RUN yarn install && yarn global add knex && yarn cache clean --all

CMD ["yarn", "dev"]