FROM node:18.12.1-buster-slim

LABEL maintainer="firman"

WORKDIR /usr/apps/logique-express-api

RUN rm -rf /var/cache/apk/*
RUN apk add --no-cache alpine-conf && \
    setup-timezone -z Asia/Jakarta

ENV NODE_ENV production
ENV TZ Asia/Jakarta

COPY package.json /usr/apps/logique-express-api
COPY ./src /usr/apps/logique-express-api

RUN yarn install --frozen-lockfile --production && yarn global add knex && yarn cache clean --all

CMD ["yarn", "start"]